### ISSUE TITLE
Fix naming convention problem that arises when you use -o to save to output directory

### ISSUE THREAD

**Issue by Jakidxav** [dlilien/ImpDAR#5]
The `-o directory_name` syntax is not available for loading in raw data. I have included two examples for SCG and Herc Dome data using Pusle Ekko and Gecko radars respectively.

With Pulse Ekko data on the HD, DT1, and GPS files:

```python
impdar load pe * -o ../raw_mat/

Traceback (most recent call last):
File "/home/jakidxav/anaconda3/bin/impdar", line 11, in <module>
load_entry_point('impdar', 'console_scripts', 'impdar')()
File "/home/jakidxav/ImpDAR/impdar/bin/impdar.py", line 113, in main
return args.func(**vars(args))
File "/home/jakidxav/ImpDAR/impdar/lib/load/__init__.py", line 100, in load_and_exit
raise ValueError('Cannot specify output with multiple inputs. Quitting without saving')
ValueError: Cannot specify output with multiple inputs. Quitting without saving
```

And with Gecko files:

```python
impdar load gecko HDGridE_x53*.gtd -o ./raw_mat/

Traceback (most recent call last):
 File "/home/jakidxav/anaconda3/bin/impdar", line 11, in <module>
    load_entry_point('impdar', 'console_scripts', 'impdar')()
 File "/home/jakidxav/ImpDAR/impdar/bin/impdar.py", line 113, in main
    return args.func(**vars(args))
 File "/home/jakidxav/ImpDAR/impdar/lib/load/__init__.py", line 101, in load_and_exit
    dat[0].save(fn_out)
 File "/home/jakidxav/ImpDAR/impdar/lib/RadarData/_RadarDataSaving.py", line 58, in save
    savemat(fn, mat)
 File "/home/jakidxav/anaconda3/lib/python3.6/site-packages/scipy/io/matlab/mio.py", line 270, in savemat
    file_stream = open(file_name, 'wb')
FileNotFoundError: [Errno 2] No such file or directory: './raw_mat/.mat'
``` 

If you don’t specify ‘./raw_mat/’ at the end, then it outputs a file called ‘raw_mat.mat’ for the line instead of creating a directory called 'raw_mat' and then saving the file(s) there.

The `-o directory_name` syntax works for every other processing step that I have tested so far, and works if you are loading in files *not* in raw format. This isn't a huge issue, since the load function correctly names raw .mat files and then stores them in the same directory. Users can then move those files over to a new directory if they want. I wanted to make note of a potential bug.

**Comment by dlilien** [comment]
OK, I agree that this is a bug. I'll work on a fix in devel.

**Comment by dlilien** [comment]
This should be fixed [here](https://github.com/dlilien/ImpDAR/commit/3c2d618f9fd7f09e46d30a47770a26b2928c4238)
