### ISSUE TITLE
Assumptions about GPS data availability

### ISSUE THREAD

**Issue by dshean** [dlilien/ImpDAR#9]
Looks like recent development assumes GPS log is available, at least for pe workflow.  Seems like some of core functionality, loading, reading, plotting, should work without GPS.
After modifications in https://github.com/dlilien/ImpDAR/pull/8, I can successfully run: `impdar load pe LINE11.DT1`
I can then run `impplot rg *mat` successfully using master branch.  But this fails on devel branch, as RadarData instance is expecting `lat` and `lon` attributes to be populated.

> impplot rg *mat
Warning: Low freq compared to sampling rate. Forcing a maximum plength
Traceback (most recent call last):
  File "/Users/dshean/sw/miniconda3/envs/shean_py3/bin/impplot", line 11, in <module>
    load_entry_point('impdar', 'console_scripts', 'impplot')()
  File "/Users/dshean/src/ImpDAR/impdar/bin/impplot.py", line 97, in main
    args.func(**vars(args))
  File "/Users/dshean/src/ImpDAR/impdar/bin/impplot.py", line 72, in plot_radargram
    plot.plot(fns, xd=xd, yd=yd, s=s, o=o, ftype=o_fmt, dpi=dpi, filetype=in_fmt, pick_colors=picks, cmap=cmap, clims=clims)
  File "/Users/dshean/src/ImpDAR/impdar/lib/plot.py", line 35, in plot
    radar_data = load(filetype, fns)
  File "/Users/dshean/src/ImpDAR/impdar/lib/load/__init__.py", line 49, in load
    dat = [RadarData(fn) for fn in fns_in]
  File "/Users/dshean/src/ImpDAR/impdar/lib/load/__init__.py", line 49, in <listcomp>
    dat = [RadarData(fn) for fn in fns_in]
  File "/Users/dshean/src/ImpDAR/impdar/lib/RadarData/__init__.py", line 156, in __init__
    self.check_attrs()
  File "/Users/dshean/src/ImpDAR/impdar/lib/RadarData/__init__.py", line 197, in check_attrs
    raise ImpdarError('{:s} needs to be a vector'.format(attr))
impdar.lib.ImpdarError.ImpdarError: lat needs to be a vector

**Comment by dlilien** [comment]
I'm closing this one since I think it is fixed on all branches
